/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression.impl;

import com.intuit.dsl.expression.ExpressionPackage;
import com.intuit.dsl.expression.UUIDFunc;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>UUID Func</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UUIDFuncImpl extends FunctionImpl implements UUIDFunc
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UUIDFuncImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressionPackage.Literals.UUID_FUNC;
  }

} //UUIDFuncImpl
