/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add To Date</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.intuit.dsl.expression.AddToDate#getDateExp <em>Date Exp</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.AddToDate#getFormat <em>Format</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.AddToDate#getExp <em>Exp</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.AddToDate#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getAddToDate()
 * @model
 * @generated
 */
public interface AddToDate extends Function
{
  /**
   * Returns the value of the '<em><b>Date Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date Exp</em>' containment reference.
   * @see #setDateExp(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getAddToDate_DateExp()
   * @model containment="true"
   * @generated
   */
  Expression getDateExp();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.AddToDate#getDateExp <em>Date Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date Exp</em>' containment reference.
   * @see #getDateExp()
   * @generated
   */
  void setDateExp(Expression value);

  /**
   * Returns the value of the '<em><b>Format</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' attribute.
   * @see #setFormat(String)
   * @see com.intuit.dsl.expression.ExpressionPackage#getAddToDate_Format()
   * @model
   * @generated
   */
  String getFormat();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.AddToDate#getFormat <em>Format</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Format</em>' attribute.
   * @see #getFormat()
   * @generated
   */
  void setFormat(String value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getAddToDate_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.AddToDate#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see com.intuit.dsl.expression.ExpressionPackage#getAddToDate_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.AddToDate#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

} // AddToDate
