/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.intuit.dsl.expression.CollectionFunction#getFunction <em>Function</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.CollectionFunction#getRefexp <em>Refexp</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.CollectionFunction#getResultKey <em>Result Key</em>}</li>
 * </ul>
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getCollectionFunction()
 * @model
 * @generated
 */
public interface CollectionFunction extends Function
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' containment reference.
   * @see #setFunction(CollectionFunctionCall)
   * @see com.intuit.dsl.expression.ExpressionPackage#getCollectionFunction_Function()
   * @model containment="true"
   * @generated
   */
  CollectionFunctionCall getFunction();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.CollectionFunction#getFunction <em>Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' containment reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(CollectionFunctionCall value);

  /**
   * Returns the value of the '<em><b>Refexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refexp</em>' containment reference.
   * @see #setRefexp(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getCollectionFunction_Refexp()
   * @model containment="true"
   * @generated
   */
  Expression getRefexp();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.CollectionFunction#getRefexp <em>Refexp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refexp</em>' containment reference.
   * @see #getRefexp()
   * @generated
   */
  void setRefexp(Expression value);

  /**
   * Returns the value of the '<em><b>Result Key</b></em>' containment reference list.
   * The list contents are of type {@link com.intuit.dsl.expression.Key}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result Key</em>' containment reference list.
   * @see com.intuit.dsl.expression.ExpressionPackage#getCollectionFunction_ResultKey()
   * @model containment="true"
   * @generated
   */
  EList<Key> getResultKey();

} // CollectionFunction
