/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concat Func</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.intuit.dsl.expression.ConcatFunc#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getConcatFunc()
 * @model
 * @generated
 */
public interface ConcatFunc extends CollectionFunctionCall
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference list.
   * The list contents are of type {@link com.intuit.dsl.expression.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference list.
   * @see com.intuit.dsl.expression.ExpressionPackage#getConcatFunc_Exp()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExp();

} // ConcatFunc
