/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Day Difference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.intuit.dsl.expression.DayDifference#getFrom <em>From</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.DayDifference#getTo <em>To</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.DayDifference#getFormatter <em>Formatter</em>}</li>
 * </ul>
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getDayDifference()
 * @model
 * @generated
 */
public interface DayDifference extends Function
{
  /**
   * Returns the value of the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' containment reference.
   * @see #setFrom(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getDayDifference_From()
   * @model containment="true"
   * @generated
   */
  Expression getFrom();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.DayDifference#getFrom <em>From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' containment reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Expression value);

  /**
   * Returns the value of the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' containment reference.
   * @see #setTo(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getDayDifference_To()
   * @model containment="true"
   * @generated
   */
  Expression getTo();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.DayDifference#getTo <em>To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' containment reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Expression value);

  /**
   * Returns the value of the '<em><b>Formatter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formatter</em>' attribute.
   * @see #setFormatter(String)
   * @see com.intuit.dsl.expression.ExpressionPackage#getDayDifference_Formatter()
   * @model
   * @generated
   */
  String getFormatter();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.DayDifference#getFormatter <em>Formatter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Formatter</em>' attribute.
   * @see #getFormatter()
   * @generated
   */
  void setFormatter(String value);

} // DayDifference
