/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends EObject
{
} // Function
