/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Func</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.intuit.dsl.expression.MapFunc#getExp <em>Exp</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.MapFunc#getRange <em>Range</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.MapFunc#getAliasKey <em>Alias Key</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.MapFunc#getReturnexp <em>Returnexp</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.MapFunc#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getMapFunc()
 * @model
 * @generated
 */
public interface MapFunc extends CollectionFunctionCall
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getMapFunc_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.MapFunc#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(Range)
   * @see com.intuit.dsl.expression.ExpressionPackage#getMapFunc_Range()
   * @model containment="true"
   * @generated
   */
  Range getRange();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.MapFunc#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(Range value);

  /**
   * Returns the value of the '<em><b>Alias Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias Key</em>' attribute.
   * @see #setAliasKey(String)
   * @see com.intuit.dsl.expression.ExpressionPackage#getMapFunc_AliasKey()
   * @model
   * @generated
   */
  String getAliasKey();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.MapFunc#getAliasKey <em>Alias Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias Key</em>' attribute.
   * @see #getAliasKey()
   * @generated
   */
  void setAliasKey(String value);

  /**
   * Returns the value of the '<em><b>Returnexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Returnexp</em>' containment reference.
   * @see #setReturnexp(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getMapFunc_Returnexp()
   * @model containment="true"
   * @generated
   */
  Expression getReturnexp();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.MapFunc#getReturnexp <em>Returnexp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Returnexp</em>' containment reference.
   * @see #getReturnexp()
   * @generated
   */
  void setReturnexp(Expression value);

  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference list.
   * The list contents are of type {@link com.intuit.dsl.expression.MapStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference list.
   * @see com.intuit.dsl.expression.ExpressionPackage#getMapFunc_Statement()
   * @model containment="true"
   * @generated
   */
  EList<MapStatement> getStatement();

} // MapFunc
