/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.intuit.dsl.expression.MapStatement#getResultKey <em>Result Key</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.MapStatement#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getMapStatement()
 * @model
 * @generated
 */
public interface MapStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Result Key</b></em>' containment reference list.
   * The list contents are of type {@link com.intuit.dsl.expression.Key}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result Key</em>' containment reference list.
   * @see com.intuit.dsl.expression.ExpressionPackage#getMapStatement_ResultKey()
   * @model containment="true"
   * @generated
   */
  EList<Key> getResultKey();

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getMapStatement_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.MapStatement#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

} // MapStatement
