/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.intuit.dsl.expression.Range#getLow <em>Low</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.Range#getDiff <em>Diff</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.Range#getHigh <em>High</em>}</li>
 * </ul>
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getRange()
 * @model
 * @generated
 */
public interface Range extends EObject
{
  /**
   * Returns the value of the '<em><b>Low</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Low</em>' containment reference.
   * @see #setLow(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getRange_Low()
   * @model containment="true"
   * @generated
   */
  Expression getLow();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.Range#getLow <em>Low</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Low</em>' containment reference.
   * @see #getLow()
   * @generated
   */
  void setLow(Expression value);

  /**
   * Returns the value of the '<em><b>Diff</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Diff</em>' attribute.
   * @see #setDiff(String)
   * @see com.intuit.dsl.expression.ExpressionPackage#getRange_Diff()
   * @model
   * @generated
   */
  String getDiff();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.Range#getDiff <em>Diff</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Diff</em>' attribute.
   * @see #getDiff()
   * @generated
   */
  void setDiff(String value);

  /**
   * Returns the value of the '<em><b>High</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>High</em>' containment reference.
   * @see #setHigh(Expression)
   * @see com.intuit.dsl.expression.ExpressionPackage#getRange_High()
   * @model containment="true"
   * @generated
   */
  Expression getHigh();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.Range#getHigh <em>High</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>High</em>' containment reference.
   * @see #getHigh()
   * @generated
   */
  void setHigh(Expression value);

} // Range
