/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schema Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.intuit.dsl.expression.SchemaVariable#getGlobal <em>Global</em>}</li>
 *   <li>{@link com.intuit.dsl.expression.SchemaVariable#getKey <em>Key</em>}</li>
 * </ul>
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getSchemaVariable()
 * @model
 * @generated
 */
public interface SchemaVariable extends EObject
{
  /**
   * Returns the value of the '<em><b>Global</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Global</em>' attribute.
   * @see #setGlobal(String)
   * @see com.intuit.dsl.expression.ExpressionPackage#getSchemaVariable_Global()
   * @model
   * @generated
   */
  String getGlobal();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.SchemaVariable#getGlobal <em>Global</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Global</em>' attribute.
   * @see #getGlobal()
   * @generated
   */
  void setGlobal(String value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' containment reference list.
   * The list contents are of type {@link com.intuit.dsl.expression.Key}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' containment reference list.
   * @see com.intuit.dsl.expression.ExpressionPackage#getSchemaVariable_Key()
   * @model containment="true"
   * @generated
   */
  EList<Key> getKey();

} // SchemaVariable
