/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UUID Func</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getUUIDFunc()
 * @model
 * @generated
 */
public interface UUIDFunc extends Function
{
} // UUIDFunc
