/**
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.expression;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.intuit.dsl.expression.Variable#getSchemaVariable <em>Schema Variable</em>}</li>
 * </ul>
 *
 * @see com.intuit.dsl.expression.ExpressionPackage#getVariable()
 * @model
 * @generated
 */
public interface Variable extends EObject
{
  /**
   * Returns the value of the '<em><b>Schema Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schema Variable</em>' containment reference.
   * @see #setSchemaVariable(SchemaVariable)
   * @see com.intuit.dsl.expression.ExpressionPackage#getVariable_SchemaVariable()
   * @model containment="true"
   * @generated
   */
  SchemaVariable getSchemaVariable();

  /**
   * Sets the value of the '{@link com.intuit.dsl.expression.Variable#getSchemaVariable <em>Schema Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schema Variable</em>' containment reference.
   * @see #getSchemaVariable()
   * @generated
   */
  void setSchemaVariable(SchemaVariable value);

} // Variable
