/*
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class ExpressionWebModule extends AbstractExpressionWebModule {
}
