/*
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ExpressionStandaloneSetup extends ExpressionStandaloneSetupGenerated {

	public static void doSetup() {
		new ExpressionStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
