/*
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExpressionScopeProvider extends DelegatingScopeProvider {
}
